common_english_nouns = [
    "time", "person", "year", "way", "day", "man", "government", "company", "hand", "part",
    "place", "case", "group", "problem", "fact", "eye", "friend", "child", "example", "family",
    "business", "question", "action", "idea", "woman", "mother", "father", "boy", "girl", "country",
    "state", "home", "fact", "book", "part", "end", "week", "month", "night", "day", "word",
    "number", "name", "sentence", "team", "way", "person", "point", "government", "company", "man",
    "woman", "child", "place", "case", "group", "problem", "fact", "hand", "part", "example",
    "friend", "eye", "family", "question", "fact", "home", "business", "body", "thing", "world",
    "life", "head", "hand", "part", "place", "case", "group", "problem", "fact", "government",
    "company", "person", "year", "point", "man", "woman", "child", "team", "country", "state",
    "problem", "fact", "home", "business", "body", "thing", "world", "life", "head", "hand",
    "part", "place", "case", "group", "problem", "fact", "government", "company", "person",
    "year", "point", "man", "woman", "child", "team", "country", "state", "problem", "fact",
    "home", "business", "body", "thing", "world", "life", "head", "hand", "place", "case",
    "group", "problem", "fact", "eye", "day", "year", "way", "week", "government", "company",
    "man", "woman", "child", "problem", "fact", "body", "thing", "word", "family", "world",
    "life", "head", "hand", "part", "place", "case", "group", "problem", "fact", "government",
    "company", "person", "year", "point", "man", "woman", "child", "team", "country", "state",
    "problem", "fact", "home", "business", "body", "thing", "world", "life", "head", "hand",
    "part", "place", "case", "group", "problem", "fact", "government", "company", "person",
    "year", "point", "man", "woman", "child", "team", "country", "state", "problem", "fact",
    "home", "business", "body", "thing", "world", "life", "head", "hand", "part", "place",
    "case", "group", "problem", "fact", "government", "company", "person", "year", "point",
    "man", "woman", "child", "team", "country", "state", "problem", "fact", "home", "business",
    "body", "thing", "world", "life", "head", "hand", "part", "place", "case", "group",
    "problem", "fact", "government", "company", "person", "year", "point", "man", "woman",
    "child", "team", "country", "state", "problem", "fact", "home", "business", "body",
    "thing", "world", "life", "head", "hand", "part", "place", "case", "group", "problem",
    "fact", "eye", "day", "year", "way", "week", "government", "company", "man", "woman",
    "child", "problem", "fact", "body", "thing", "word", "family", "world", "life", "head",
    "hand", "part", "place", "case", "group", "problem", "fact", "government", "company",
    "person", "year", "point", "man", "woman", "child", "team", "country", "state", "problem",
    "fact", "home", "business", "body", "thing", "world", "life", "head", "hand", "part",
    "place", "case", "group", "problem", "fact", "government", "company", "person", "year",
    "point", "man", "woman", "child", "team", "country", "state", "problem", "fact", "home",
    "business", "body", "thing", "world", "life", "head", "hand", "part", "place", "case",
    "group", "problem", "fact", "government", "company", "person", "year", "point", "man",
    "woman", "child", "team", "country", "state", "problem", "fact", "home", "business",
    "body", "thing", "world", "life", "head", "hand", "part", "place", "case", "group",
    "problem", "fact", "government", "company", "person", "year", "point", "man", "woman",
    "child", "team", "country", "state", "problem", "fact", "home", "business", "body",
    "thing", "world", "life", "head", "hand", "part", "place", "case", "group", "problem",
    "fact", "eye", "day", "year", "way", "week", "government", "company", "man", "woman",
    "child", "problem", "fact", "body", "thing", "word", "family", "world", "life", "head",
    "hand", "part", "place", "case", "group", "problem", "fact", "government", "company",
    "person", "year", "point", "man", "woman", "child", "team", "country", "state", "problem",
    "fact", "home", "business", "body", "thing", "world", "life", "head", "hand", "part",
    "place", "case", "group", "problem", "fact", "government", "company", "person", "year",
    "point", "man", "woman", "child", "team", "country", "state", "problem", "fact", "home",
    "business", "body", "thing", "world", "life", "head", "hand", "part", "place", "case",
    "group", "problem", "fact", "government", "company", "person", "year", "point"]
